#!/bin/bash
#SBATCH -J ARGsOAP_stage1
#SBATCH -o ARGsOAP_stage1.%j.out
#SBATCH -e ARGsOAP_stage1.%j.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --time=3-00:00:00

# ============================================================
# ARGs-OAP Stage One analysis
# Shotgun metagenomic data from dairy cow fecal samples
#
# Input:
#   Host-filtered paired-end reads generated by KneadData
#
# Output:
#   ARGs-OAP Stage One results for downstream ARG profiling
# ============================================================

set -euo pipefail

THREADS=20

# Modify this path according to the local computing environment
PROJECT_DIR="/path/to/DairyCow-TraceMineral-Resistome"

INPUT_DIR="${PROJECT_DIR}/metagenome/02kneaddata"
OUTPUT_DIR="${PROJECT_DIR}/metagenome/ARGsOAP/stage_one"

mkdir -p "${OUTPUT_DIR}"

echo "Starting ARGs-OAP Stage One..."

args_oap stage_one \
    -i "${INPUT_DIR}" \
    -o "${OUTPUT_DIR}" \
    -f fastq \
    -t "${THREADS}"

echo "ARGs-OAP Stage One completed successfully."