#!/bin/bash
#SBATCH -J ARGsOAP_stage2
#SBATCH -o ARGsOAP_stage2.%j.out
#SBATCH -e ARGsOAP_stage2.%j.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mem=100G
#SBATCH --time=3-00:00:00

# ============================================================
# ARGs-OAP Stage Two analysis
# Shotgun metagenomic data from dairy cow fecal samples
#
# Samples: a1-a120
#
# Input:
#   Output generated by ARGs-OAP Stage One
#
# Output:
#   ARG abundance and annotation results for downstream
#   resistome analyses
#
# Before running:
#   1. Make sure ARGs-OAP is available in $PATH
#   2. Modify PROJECT_DIR according to the local environment
# ============================================================

set -euo pipefail

# --------------------------
# Parameters
# --------------------------
THREADS=20

PROJECT_DIR="/path/to/DairyCow-TraceMineral-Resistome"

INPUT_DIR="${PROJECT_DIR}/metagenome/ARGsOAP/stage_one"
OUTPUT_DIR="${PROJECT_DIR}/metagenome/ARGsOAP/stage_two"

mkdir -p "${OUTPUT_DIR}"

echo "=========================================="
echo "Starting ARGs-OAP Stage Two"
echo "Samples         : a1-a120"
echo "Input directory : ${INPUT_DIR}"
echo "Output directory: ${OUTPUT_DIR}"
echo "Threads         : ${THREADS}"
echo "=========================================="

# --------------------------
# Run ARGs-OAP Stage Two
# --------------------------
args_oap stage_two \
    -i "${INPUT_DIR}" \
    -o "${OUTPUT_DIR}" \
    -t "${THREADS}"

echo "=========================================="
echo "ARGs-OAP Stage Two completed successfully."
echo "=========================================="