#!/bin/bash
#SBATCH -J BacMet_stage1
#SBATCH -o BacMet_stage1.%j.out
#SBATCH -e BacMet_stage1.%j.err
#SBATCH --cpus-per-task=20
#SBATCH --time=300:00:00

# ============================================================
# BacMet Stage One analysis
# Shotgun metagenomic data from dairy cow fecal samples
#
# Samples: a1-a120
#
# Input:
#   Host-filtered paired-end reads generated by KneadData
#
# Output:
#   BacMet Stage One results for downstream metal resistance
#   gene (MRG) profiling
#
# Before running:
#   1. Modify PROJECT_DIR according to the local environment
#   2. Set BACMET_PIPELINE to the local installation of the
#      BacMet Stage One pipeline
#   3. Prepare the metadata file with the correct sample-group
#      assignments
# ============================================================

set -euo pipefail

# --------------------------
# Parameters
# --------------------------
THREADS=20

PROJECT_DIR="/path/to/DairyCow-TraceMineral-Resistome"

INPUT_DIR="${PROJECT_DIR}/metagenome/02_kneaddata"
OUTPUT_DIR="${PROJECT_DIR}/metagenome/BacMet/stage_one"
STAGE_DIR="${PROJECT_DIR}/metagenome/BacMet/stage_one_input"

# Custom BacMet Stage One pipeline
BACMET_PIPELINE="/path/to/argoap_pipeline_stageone_version2_BacMet"

# Metadata file containing at least:
# SampleID    Group
METADATA_FILE="${PROJECT_DIR}/metadata/bacmet_metadata_map.txt"

mkdir -p "${OUTPUT_DIR}"
mkdir -p "${STAGE_DIR}"

# --------------------------
# Prepare paired-end input
# --------------------------
echo ">>> Preparing paired-end reads..."

rm -f "${STAGE_DIR}"/*_1.fq "${STAGE_DIR}"/*_2.fq 2>/dev/null || true

for ID in {1..120}; do

    SAMPLE="a${ID}"

    R1="${INPUT_DIR}/${SAMPLE}_kneaddata_paired_1.fastq"
    R2="${INPUT_DIR}/${SAMPLE}_kneaddata_paired_2.fastq"

    if [[ ! -f "${R1}" || ! -f "${R2}" ]]; then
        echo "ERROR: Missing paired-end files for ${SAMPLE}"
        exit 1
    fi

    ln -sf "${R1}" "${STAGE_DIR}/${SAMPLE}_1.fq"
    ln -sf "${R2}" "${STAGE_DIR}/${SAMPLE}_2.fq"

done

echo ">>> Prepared paired-end reads for 120 samples."

# --------------------------
# Check metadata
# --------------------------
if [[ ! -f "${METADATA_FILE}" ]]; then
    echo "ERROR: Metadata file not found:"
    echo "${METADATA_FILE}"
    exit 1
fi

# --------------------------
# Run BacMet Stage One
# --------------------------
echo ">>> Starting BacMet Stage One..."

"${BACMET_PIPELINE}" \
    -i "${STAGE_DIR}" \
    -m "${METADATA_FILE}" \
    -o "${OUTPUT_DIR}" \
    -n "${THREADS}" \
    -f fq

echo ">>> BacMet Stage One completed successfully."