#!/bin/bash
#SBATCH -J MGE_stage1
#SBATCH -o MGE_stage1.%j.out
#SBATCH -e MGE_stage1.%j.err
#SBATCH --cpus-per-task=20
#SBATCH --time=300:00:00

# ============================================================
# MGE Stage One analysis
# Shotgun metagenomic data from dairy cow fecal samples
#
# Samples: a1-a120
#
# Input:
#   Host-filtered paired-end reads generated by KneadData
#
# Output:
#   Stage One results for downstream mobile genetic element
#   (MGE) profiling
#
# Before running:
#   1. Make sure the required pipeline and dependencies
#      are installed and available.
#   2. Modify PROJECT_DIR and MGE_PIPELINE according to
#      the local computing environment.
# ============================================================

set -euo pipefail

# --------------------------
# Parameters
# --------------------------
THREADS=20

PROJECT_DIR="/path/to/DairyCow-TraceMineral-Resistome"

# KneadData output
INPUT_DIR="${PROJECT_DIR}/metagenome/02_kneaddata"

# MGE Stage One output
OUTPUT_DIR="${PROJECT_DIR}/metagenome/MGE/stage_one"

# Temporary directory containing renamed symbolic links
STAGE_DIR="${PROJECT_DIR}/metagenome/MGE/stage_one_input"

# MGE Stage One pipeline
MGE_PIPELINE="/path/to/argoap_pipeline_stageone_version2_MGE"

mkdir -p "${OUTPUT_DIR}"
mkdir -p "${STAGE_DIR}"

METADATA="${OUTPUT_DIR}/metadata_map.txt"

# --------------------------
# Remove old symbolic links
# --------------------------
rm -f "${STAGE_DIR}"/*_1.fq "${STAGE_DIR}"/*_2.fq 2>/dev/null || true

# --------------------------
# Prepare input files
# Samples: a1-a120
# --------------------------
echo -e "SampleID\tGroup" > "${METADATA}"

echo ">>> Preparing MGE Stage One input..."

for ID in {1..120}; do

    SAMPLE="a${ID}"

    R1="${INPUT_DIR}/${SAMPLE}_kneaddata_paired_1.fastq"
    R2="${INPUT_DIR}/${SAMPLE}_kneaddata_paired_2.fastq"

    # Check paired-end files
    if [[ ! -f "${R1}" ]]; then
        echo "ERROR: Missing R1 file: ${R1}"
        exit 1
    fi

    if [[ ! -f "${R2}" ]]; then
        echo "ERROR: Missing R2 file: ${R2}"
        exit 1
    fi

    # Create symbolic links using the naming convention
    # required by the MGE pipeline
    ln -sf "${R1}" "${STAGE_DIR}/${SAMPLE}_1.fq"
    ln -sf "${R2}" "${STAGE_DIR}/${SAMPLE}_2.fq"

    # The Group column is required by the Stage One pipeline.
    # Sample IDs are used here because group information is not
    # required for sequence annotation at this stage.
    echo -e "${SAMPLE}\t${SAMPLE}" >> "${METADATA}"

done

echo ">>> Prepared 120 samples."
echo ">>> Metadata file: ${METADATA}"

# --------------------------
# Run MGE Stage One
# --------------------------
echo ">>> Running MGE Stage One..."

"${MGE_PIPELINE}" \
    -i "${STAGE_DIR}" \
    -m "${METADATA}" \
    -o "${OUTPUT_DIR}" \
    -n "${THREADS}" \
    -f fq

echo ">>> MGE Stage One completed successfully."
