#!/bin/bash
#SBATCH -J MGE_stage2
#SBATCH -o MGE_stage2.%j.out
#SBATCH -e MGE_stage2.%j.err
#SBATCH --cpus-per-task=20
#SBATCH --time=300:00:00

# ============================================================
# MGE Stage Two analysis
# Shotgun metagenomic data from dairy cow fecal samples
#
# Samples: a1-a120
#
# Input:
#   Output generated by MGE Stage One
#
# Required files:
#   extracted.fa
#   meta_data_online.txt
#
# Output:
#   MGE Stage Two results for downstream mobilome analyses
#
# Before running:
#   1. Make sure the required pipeline and dependencies
#      are installed.
#   2. Modify PROJECT_DIR and MGE_PIPELINE according to
#      the local computing environment.
# ============================================================

set -euo pipefail

# --------------------------
# Parameters
# --------------------------
THREADS=20

PROJECT_DIR="/path/to/DairyCow-TraceMineral-Resistome"

# MGE Stage One output
INPUT_DIR="${PROJECT_DIR}/metagenome/MGE/stage_one"

# MGE Stage Two output
OUTPUT_DIR="${PROJECT_DIR}/metagenome/MGE/stage_two"

# MGE Stage Two pipeline
MGE_PIPELINE="/path/to/argoap_pipeline_stagetwo_version2_MGE"

# --------------------------
# Input files
# --------------------------
EXTRACTED_FASTA="${INPUT_DIR}/extracted.fa"
METADATA="${INPUT_DIR}/meta_data_online.txt"
METADATA_NUMERIC="${INPUT_DIR}/meta_data_online.numeric.txt"

mkdir -p "${OUTPUT_DIR}"

# --------------------------
# Check required files
# --------------------------
if [[ ! -f "${EXTRACTED_FASTA}" ]]; then
    echo "ERROR: ${EXTRACTED_FASTA} not found."
    exit 1
fi

if [[ ! -f "${METADATA}" ]]; then
    echo "ERROR: ${METADATA} not found."
    exit 1
fi

# --------------------------
# Convert the first metadata column
# to sequential numeric IDs
#
# Header is retained unchanged.
# The first column of each data row is
# replaced by 1, 2, 3, ...
# --------------------------
echo ">>> Preparing numeric metadata..."

awk 'BEGIN{FS=OFS="\t"}
     NR==1 {print; next}
     {$1=NR-1; print}' \
    "${METADATA}" > "${METADATA_NUMERIC}"

# --------------------------
# Run MGE Stage Two
# --------------------------
echo ">>> Starting MGE Stage Two..."
echo "Samples         : a1-a120"
echo "Input directory : ${INPUT_DIR}"
echo "Output directory: ${OUTPUT_DIR}"

"${MGE_PIPELINE}" \
    -i "${EXTRACTED_FASTA}" \
    -m "${METADATA_NUMERIC}" \
    -o "${OUTPUT_DIR}" \
    -n "${THREADS}"

echo ">>> MGE Stage Two completed successfully."