#!/bin/bash
#SBATCH -J metaSPAdes
#SBATCH -o metaSPAdes.%j.out
#SBATCH -e metaSPAdes.%j.err
#SBATCH --cpus-per-task=20
#SBATCH --mem=800G
#SBATCH --time=168:00:00

# ============================================================
# Metagenomic assembly using metaSPAdes
# Shotgun metagenomic data from dairy cow fecal samples
#
# Samples: a1-a120
#
# Input:
#   Host-filtered paired-end reads generated by KneadData
#
# Output:
#   Metagenomic assemblies for downstream ORF prediction,
#   MRG/MGE annotation, and genomic-context analyses
#
# Before running:
#   1. Make sure SPAdes/metaSPAdes is available in $PATH.
#   2. Modify PROJECT_DIR according to the local environment.
# ============================================================

set -euo pipefail

# --------------------------
# Parameters
# --------------------------
THREADS=20
MEMORY_GB=800

PROJECT_DIR="/path/to/DairyCow-TraceMineral-Resistome"

# KneadData output
INPUT_DIR="${PROJECT_DIR}/metagenome/02_kneaddata"

# metaSPAdes output
OUTPUT_DIR="${PROJECT_DIR}/metagenome/assembly/metaSPAdes"

mkdir -p "${OUTPUT_DIR}"

# --------------------------
# Assemble samples a1-a120
# --------------------------
for ID in {1..120}; do

    SAMPLE="a${ID}"

    R1="${INPUT_DIR}/${SAMPLE}_kneaddata_paired_1.fastq"
    R2="${INPUT_DIR}/${SAMPLE}_kneaddata_paired_2.fastq"

    SAMPLE_OUT="${OUTPUT_DIR}/${SAMPLE}"

    echo ">>> Processing ${SAMPLE}..."

    # Check paired-end input files
    if [[ ! -f "${R1}" ]]; then
        echo "ERROR: Missing R1 file: ${R1}"
        exit 1
    fi

    if [[ ! -f "${R2}" ]]; then
        echo "ERROR: Missing R2 file: ${R2}"
        exit 1
    fi

    mkdir -p "${SAMPLE_OUT}"

    # --------------------------
    # Run metaSPAdes
    # --------------------------
    spades.py \
        --meta \
        -1 "${R1}" \
        -2 "${R2}" \
        -o "${SAMPLE_OUT}" \
        -t "${THREADS}" \
        -m "${MEMORY_GB}"

    echo ">>> Finished ${SAMPLE}"

done

echo ">>> metaSPAdes assembly completed for all samples."