#!/bin/bash
#SBATCH -J HUMAnN
#SBATCH -o HUMAnN.%j.out
#SBATCH -e HUMAnN.%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=400G
#SBATCH --time=120:00:00

# ============================================================
# Functional profiling of shotgun metagenomic reads using HUMAnN
#
# Samples: a1-a120
#
# Input:
#   Host-filtered paired-end reads generated by KneadData
#
# Output:
#   Gene family, pathway abundance, and pathway coverage profiles
#   for downstream MetaCyc pathway analyses
#
# Before running:
#   1. Make sure HUMAnN and MetaPhlAn are available in $PATH.
#   2. Modify PROJECT_DIR according to the local environment.
#   3. Set METAPHLAN_DB to the local MetaPhlAn database.
# ============================================================

set -euo pipefail

# --------------------------
# Parameters
# --------------------------
THREADS=8

PROJECT_DIR="/path/to/DairyCow-TraceMineral-Resistome"

INPUT_DIR="${PROJECT_DIR}/metagenome/02_kneaddata"
OUTPUT_DIR="${PROJECT_DIR}/metagenome/HUMAnN"

# MetaPhlAn database
METAPHLAN_DB="/path/to/MetaPhlAn/database"
METAPHLAN_INDEX="mpa_vOct22_CHOCOPhlAnSGB_202212"

mkdir -p "${OUTPUT_DIR}"

# --------------------------
# Process samples a1-a120
# --------------------------
for ID in {1..120}; do

    SAMPLE="a${ID}"

    R1="${INPUT_DIR}/${SAMPLE}_kneaddata_paired_1.fastq"
    R2="${INPUT_DIR}/${SAMPLE}_kneaddata_paired_2.fastq"

    SAMPLE_OUT="${OUTPUT_DIR}/${SAMPLE}"
    MERGED="${SAMPLE_OUT}/${SAMPLE}_merged.fastq"

    echo ">>> Running HUMAnN for ${SAMPLE}..."

    if [[ ! -f "${R1}" || ! -f "${R2}" ]]; then
        echo "WARNING: Missing paired-end reads for ${SAMPLE}. Skipping."
        continue
    fi

    mkdir -p "${SAMPLE_OUT}"

    # HUMAnN accepts a single sequence file as input.
    # Paired-end reads are concatenated before functional profiling.
    cat "${R1}" "${R2}" > "${MERGED}"

    humann \
        --input "${MERGED}" \
        --output "${SAMPLE_OUT}" \
        --threads "${THREADS}" \
        --metaphlan-options "--bowtie2db ${METAPHLAN_DB} --index ${METAPHLAN_INDEX} --offline" \
        --remove-temp-output

    rm -f "${MERGED}"

    echo ">>> Finished ${SAMPLE}"

done

echo ">>> HUMAnN profiling completed for all samples."